-- ---------------------------------------------------------------------------
-- pedidos_itens_faltantes — o que FALTA no estoque para produzir cada peça
--
-- Gravada UMA VEZ, no momento da conversão do orçamento em pedido. É a foto do
-- que foi decidido naquele instante e não deve ser recalculada depois: o
-- relatório de produção, o estorno e as escolhas do cancelamento precisam ver
-- exatamente o que o usuário viu quando confirmou.
--
-- O registro é POR PEÇA (pedido_item_id), como já é feito em pedido_itens_ext.
-- O processo é gravado junto em cada linha, então o relatório agrupa por
-- processo e soma as quantidades sem precisar refazer a rota do produto.
--
-- Os nomes (insumo, unidade, processo) são CONGELADOS de propósito. Renomear um
-- insumo meses depois não pode reescrever a história de um pedido já produzido.
-- Os ids (insumo_id, etapa_id) ficam para ligação e conferência, e podem ser
-- nulos quando a rota não resolveu o cadastro.
--
-- COMO RODAR: no pgAdmin, conectado ao banco Santissimo_Decor_App_Gestao,
-- abra este arquivo e execute. É idempotente — pode rodar de novo sem erro.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.pedidos_itens_faltantes (
    -- IDENTITY "BY DEFAULT" (e não "ALWAYS") de propósito: o app grava em
    -- várias tabelas com id explícito (getMaxId + inserirLinhaComId, porque
    -- pedidos_itens e afins não têm auto-incremento). Assim os dois caminhos
    -- funcionam — omitir o id e deixar o banco gerar, ou mandar um id pronto.
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A quem pertence
    pedido_id         bigint        NOT NULL,
    pedido_item_id    bigint        NOT NULL,   -- a peça (linha de pedidos_itens)
    produto_id        bigint,                   -- redundante, evita join no relatório

    -- O insumo que falta
    insumo_id         bigint,                   -- materia_prima.id, quando conhecido
    insumo_nome       text          NOT NULL,   -- congelado na conversão
    unidade           text,                     -- congelada na conversão

    -- Onde ele entra na produção
    etapa_id          bigint,                   -- etapas_producao.id, quando conhecido
    processo          text          NOT NULL,   -- nome do processo, congelado
    ordem_insumo      integer,                  -- posição na rota do produto

    -- Quanto falta PARA ESTA PEÇA (o total por processo é soma, feita no app)
    quantidade        numeric(12,4) NOT NULL,

    criado_em         timestamp     NOT NULL DEFAULT now(),

    CONSTRAINT pedidos_itens_faltantes_quantidade_positiva
        CHECK (quantidade > 0)
);

-- ---------------------------------------------------------------------------
-- Índices
--
-- O relatório sempre entra por pedido e agrupa por processo; o estorno e o
-- cancelamento entram pela peça.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_pif_pedido
    ON public.pedidos_itens_faltantes (pedido_id);

CREATE INDEX IF NOT EXISTS idx_pif_pedido_processo
    ON public.pedidos_itens_faltantes (pedido_id, processo);

CREATE INDEX IF NOT EXISTS idx_pif_pedido_item
    ON public.pedidos_itens_faltantes (pedido_item_id);

CREATE INDEX IF NOT EXISTS idx_pif_insumo
    ON public.pedidos_itens_faltantes (insumo_id);

-- Uma linha por (peça, insumo, processo). Se a conversão for reexecutada, o
-- app atualiza a linha em vez de duplicar o faltante.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pif_peca_insumo
    ON public.pedidos_itens_faltantes (pedido_item_id, insumo_nome, processo);

-- ---------------------------------------------------------------------------
-- Chaves estrangeiras
--
-- Ficam por último e cada uma no seu bloco: se pedidos_itens não tiver chave
-- primária em "id" no seu banco, apenas ESTA constraint falha — a tabela e os
-- índices acima continuam criados e o recurso funciona igual. Nesse caso, ou
-- crie a PK que falta, ou simplesmente ignore o aviso.
--
-- ON DELETE CASCADE: o faltante não tem vida própria. Apagou o pedido ou a
-- peça, o registro do que faltava para produzi-la deixa de fazer sentido.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_pif_pedido'
    ) THEN
        ALTER TABLE public.pedidos_itens_faltantes
            ADD CONSTRAINT fk_pif_pedido
            FOREIGN KEY (pedido_id) REFERENCES public.pedidos (id)
            ON DELETE CASCADE;
    END IF;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'fk_pif_pedido nao criada (%): a tabela funciona sem ela.', SQLERRM;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_pif_pedido_item'
    ) THEN
        ALTER TABLE public.pedidos_itens_faltantes
            ADD CONSTRAINT fk_pif_pedido_item
            FOREIGN KEY (pedido_item_id) REFERENCES public.pedidos_itens (id)
            ON DELETE CASCADE;
    END IF;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'fk_pif_pedido_item nao criada (%): a tabela funciona sem ela.', SQLERRM;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_pif_insumo'
    ) THEN
        ALTER TABLE public.pedidos_itens_faltantes
            ADD CONSTRAINT fk_pif_insumo
            FOREIGN KEY (insumo_id) REFERENCES public.materia_prima (id)
            ON DELETE SET NULL;
    END IF;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'fk_pif_insumo nao criada (%): a tabela funciona sem ela.', SQLERRM;
END $$;

-- ---------------------------------------------------------------------------
-- Documentação no próprio banco
-- ---------------------------------------------------------------------------
COMMENT ON TABLE public.pedidos_itens_faltantes IS
    'Insumos que faltavam no estoque para produzir cada peça, congelados no momento da conversão do orçamento em pedido. Base do relatório de produção e do estorno no cancelamento.';
COMMENT ON COLUMN public.pedidos_itens_faltantes.pedido_item_id IS
    'Peça (pedidos_itens.id). O agrupamento por processo é feito somando as linhas.';
COMMENT ON COLUMN public.pedidos_itens_faltantes.insumo_nome IS
    'Nome congelado na conversão: renomear o insumo depois não reescreve o histórico.';
COMMENT ON COLUMN public.pedidos_itens_faltantes.processo IS
    'Nome do processo congelado na conversão. O relatório usa uma folha por processo.';
COMMENT ON COLUMN public.pedidos_itens_faltantes.quantidade IS
    'Quantidade faltante para ESTA peça. O total do processo é a soma das peças.';

-- ---------------------------------------------------------------------------
-- Conferência rápida (opcional)
-- ---------------------------------------------------------------------------
-- SELECT processo, insumo_nome, unidade, SUM(quantidade) AS falta_total
--   FROM public.pedidos_itens_faltantes
--  WHERE pedido_id = 47
--  GROUP BY processo, insumo_nome, unidade
--  ORDER BY processo, insumo_nome;
