-- ---------------------------------------------------------------------------
-- pedido_itens_ext: fazer o INSERT funcionar
--
-- Sintoma: `POST /api/pedido_itens_ext` devolve 500, enquanto
-- `pedidos_itens_faltantes` grava normalmente no MESMO request, pelo MESMO
-- cliente. As permissões das duas são idênticas (você conferiu).
--
-- A diferença entre elas é UMA: `pedidos_itens_faltantes.id` foi criada por mim
-- com `GENERATED BY DEFAULT AS IDENTITY`; `pedido_itens_ext.id` é um bigint
-- NOT NULL **sem default**. Um INSERT sem `id` viola NOT NULL e a API devolve
-- 500 em vez de repassar o erro do banco.
--
-- Este arquivo dá a ela o mesmo comportamento da tabela que funciona.
--
-- COMO RODAR: pgAdmin, arquivo inteiro. É idempotente.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- 1. Diagnóstico — rode primeiro e confira a coluna "tem_default"
--
-- Se `pedido_itens_ext` aparecer com tem_default = NO e
-- `pedidos_itens_faltantes` com YES, está confirmado.
-- ===========================================================================
SELECT c.table_name,
       c.column_name,
       c.data_type,
       c.is_nullable,
       CASE WHEN c.column_default IS NOT NULL OR c.is_identity = 'YES'
            THEN 'YES' ELSE 'NO' END AS tem_default,
       c.is_identity,
       c.column_default
  FROM information_schema.columns c
 WHERE c.table_schema = 'public'
   AND c.table_name IN ('pedido_itens_ext', 'pedidos_itens_faltantes')
   AND c.column_name = 'id';


-- ===========================================================================
-- 2. A correção
--
-- Transforma `id` em IDENTITY "BY DEFAULT" — o mesmo da tabela que funciona.
-- "BY DEFAULT" (e não "ALWAYS") de propósito: o app tem código que grava com
-- id explícito em várias tabelas, e assim os dois caminhos continuam válidos.
--
-- A sequência começa depois do maior id existente, para não colidir com o que
-- já estiver gravado.
-- ===========================================================================
DO $$
DECLARE
    proximo bigint;
BEGIN
    -- Já é identity? Não há o que fazer.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = 'pedido_itens_ext'
           AND column_name = 'id'
           AND is_identity = 'YES'
    ) THEN
        RAISE NOTICE 'pedido_itens_ext.id ja e IDENTITY: nada a fazer.';
        RETURN;
    END IF;

    -- Um default antigo (sequence solta) também resolve; troca por identity.
    EXECUTE 'ALTER TABLE public.pedido_itens_ext ALTER COLUMN id DROP DEFAULT';

    SELECT COALESCE(MAX(id), 0) + 1 INTO proximo FROM public.pedido_itens_ext;

    EXECUTE format(
        'ALTER TABLE public.pedido_itens_ext ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
        proximo
    );

    RAISE NOTICE 'pedido_itens_ext.id agora e IDENTITY, comecando em %.', proximo;
END $$;


-- ===========================================================================
-- 3. Conferência — rode de novo o bloco 1.
--    `pedido_itens_ext` deve aparecer com is_identity = YES.
--
-- Se DEPOIS disso o POST continuar dando 500, o problema não é o id: é a rota
-- da API upstream para esta tabela. Nesse caso o teste decisivo é comparar as
-- duas chamadas direto, fora do app:
--
--   POST {sua_api}/api/pedidos_itens_faltantes   -> funciona
--   POST {sua_api}/api/pedido_itens_ext          -> 500
--
-- Mesmo corpo mínimo, mesmo token. Se a segunda falhar sozinha, é
-- configuração da API, não do banco nem do app.
-- ===========================================================================
